### ISSUE TITLE
Cannot download your package

### ISSUE THREAD

**Issue by ccnawrocki** [TileDB-Inc/tiledbsc#101]
Hello, 
I am following the following vignette from Nanostring CosMx, which uses your package: 
https://nanostring.com/wp-content/uploads/2023/01/LiverPublicDataRelease.html#SeuratObject

When I try to download your package with the following code: 

`library(devtools)`
`install_github("tiledb-inc/tiledbsc", force = TRUE)`

I get this error message: 
<img width="1040" alt="Screen Shot 2023-05-22 at 5 35 13 PM" src="https://github.com/TileDB-Inc/tiledbsc/assets/68296470/599c9f52-060e-4f16-8ef9-94301ee2c95c">

What am I doing wrong?

**Comment by eddelbuettel** [comment]
Hi @ccnawrocki -- Thanks for posting, and sorry about the failed install.  We cannot tell yet what is happening (and I do not have a macOS machine with R 4.1 handy).  When R say 'lazy loading failed' it typically means that the final step of package building (a check of loading the package) failed, but it does not show the reason.  It would be helpful for us to see the complete log (as text, not a screenshot).  On my machine (R 4.3.0, Ubuntu) it all passes cleanly:

```r
> remotes::install_github("tiledb-inc/tiledbsc")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo tiledb-inc/tiledbsc@HEAD
Skipping 4 packages ahead of CRAN: Rcpp, RcppSpdlog, RcppEigen, tiledb
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/RtmpXO3C9S/remotes37adeb50704022/TileDB-Inc-tiledbsc-ff6c998/DESCRIPTION’ ...
─  preparing ‘tiledbsc’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘tiledbsc_0.1.5.9001.tar.gz’
   
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘tiledbsc’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (tiledbsc)
> library(tiledbsc)
> 
```

**Comment by ccnawrocki** [comment]
Hi, sorry for the delay. 
I am using macOS and my mac is an M1 mac. Here is the full text: 

> remotes::install_github("tiledb-inc/tiledbsc", force = TRUE)
Downloading GitHub repo tiledb-inc/tiledbsc@HEAD
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/_6/qhytbgh10k5cp65dy9zhhcym0000gp/T/RtmpPdLlsw/remotesbdb3700c06a4/TileDB-Inc-tiledbsc-ff6c998/DESCRIPTION’ ...
─  preparing ‘tiledbsc’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘tiledbsc_0.1.5.9001.tar.gz’
   
Installing package into ‘/Users/cnawrocki/Library/R/x86_64/4.1/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘tiledbsc’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘Matrix’ 1.5-1 is being loaded, but >= 1.5.3 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘tiledbsc’
* removing ‘/Users/cnawrocki/Library/R/x86_64/4.1/library/tiledbsc’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/_6/qhytbgh10k5cp65dy9zhhcym0000gp/T//RtmpPdLlsw/filebdb325883274/tiledbsc_0.1.5.9001.tar.gz’ had non-zero exit status
>

**Comment by eddelbuettel** [comment]
As shown in the log you are violating a stated installation requirement:

> namespace ‘Matrix’ 1.5-1 is being loaded, but >= 1.5.3 is required

Please try upgrading package `Matrix` (from CRAN) and try again.  If it still fails, please post again a full log.

**Comment by ccnawrocki** [comment]
I have literally been trying for hours to update the package, and it just keeps failing. I just keep getting the following. I cannot copy and paste the entire thing, as it is too long: 

ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Matrix.so] Error 1
ERROR: compilation failed for package ‘Matrix’
* removing ‘/Users/cnawrocki/Library/R/x86_64/4.1/library/Matrix’
* restoring previous ‘/Users/cnawrocki/Library/R/x86_64/4.1/library/Matrix’
Warning in install.packages :
  installation of package ‘Matrix’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/_6/qhytbgh10k5cp65dy9zhhcym0000gp/T/Rtmphio2ys/downloaded_packages’


What is this error? I am sure other people will run into this problem. Anything you can do to help?

**Comment by eddelbuettel** [comment]
You do not have the Fortran compiler configured correctly, so building from source does not work.  

Have you tried installing `Matrix` as a binary from CRAN?  There are these:

![image](https://github.com/TileDB-Inc/tiledbsc/assets/673121/edbe3e6c-ee6b-4d86-8d71-7126536b9e8e)

Once you have `Matrix`, installing `tiledbsc` from the repo should be easy as there is no compilation.

**Comment by ccnawrocki** [comment]
To be honest, I don't know how to do install as a binary from CRAN

**Comment by ccnawrocki** [comment]
Nevermind, I figured it out. Thank you very much for the help!

**Comment by eddelbuettel** [comment]
Glad to hear you are sorted out.  I will close this now.  Should have other issue, please do not hesitate to open another issue ticket.  We also offers a community via the link at the bottom of the company webpage.
