### ISSUE TITLE
When to transition from user- to tiledb / FOM conventions?

### ISSUE THREAD

**Issue by mtmorgan** [TileDB-Inc/tiledbsc#32]
I’m not sure what the right answer is, but is it appropriate to use Bioconductor (for example) terminology rather than TileDB terminology in, e.g., `…$to_single_cell_experiment()`, e.g., calling the argument `assays = c(…)` rather than `layers = …` so that it is maximally friendly to the corresponding user community, rather than to the TileDB developer?

**Comment by aaronwolen** [comment]
Thanks for the comment, @mtmorgan! This is great feedback. There's a tension between remaining internally consistent with the matrix-api spec and adopting conventions from other toolchains. But this is an important point and I'll leave this issue open so others can weigh in.

**Comment by aaronwolen** [comment]
Closing this now that we have settled on a set of framework/backend agnostic conventions in the updated [SOMA spec](https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md).
