### ISSUE TITLE
Add filters for data ingest

### ISSUE THREAD

**Issue by johnkerl** [TileDB-Inc/tiledbsc#48]
Following from learnings at https://github.com/single-cell-data/TileDB-SingleCell/tree/main/apis/python this week

**Comment by aaronwolen** [comment]
Need to make the following changes:

- set `obs` tile extent to 256
- set `var` tile extent to 2048
- set zstd level to 22 on the `var_id` dimension of `X` arrays
- increase `X` array capacity from 1e4 to 1e5
- set `X` cell order to column major (tile order remains row major)

Did I miss anything @johnkerl?

**Comment by johnkerl** [comment]
@aaronwolen:

* `tile_order` and `cell_order` both `row-major` (CZI default `tile_order` is `col-major` but that ran into a [core bug](https://github.com/TileDB-Inc/TileDB/pull/3143))
* `offsets_filters=[tiledb.DoubleDeltaFilter(), tiledb.BitWidthReductionFilter(), tiledb.ZstdFilter()]` for

**Comment by aaronwolen** [comment]
Closed by #50
