### ISSUE TITLE
Relationship to `single-cell-data/TileDB-SOMA`?

### ISSUE THREAD

**Issue by multimeric** [TileDB-Inc/tiledbsc#94]
I'm looking into using TileDB for single cell data in R. Should I be looking here, or in https://github.com/single-cell-data/TileDB-SOMA? It's very confusing to me as both seem to be maintained, and both involve TileDB-Inc.

**Comment by aaronwolen** [comment]
Hi @multimeric, thanks for your question!

This repo contains our original single-cell API that we continue to maintain for our customers and users. The single-cell-data/TileDB-SOMA repo contains the next major version of our single-cell application that's being developed in collaboration with CZI. We recently cut a 1.0 RC for the new TileDB-SOMA python package—if you're a Python user, we'd love to have you kick the tires and provide any feedback you have. The R package is still a WIP but we expect it to hit 1.0 in the next month or two. 

Please let me know if you have any other questions.

**Comment by multimeric** [comment]
Thanks, that clarifies a lot!
